export type Shortcut = {
  name: string;
  desc: string;
  keys: string[];
};

export const getShortcutsData = (t: any): Shortcut[] => [
  { name: t("settings.shortcuts.archiveChat"), desc: t("settings.shortcuts.archiveChatDesc"), keys: ["Ctrl+Shift+A"] },
  { name: t("settings.shortcuts.newChat"), desc: t("settings.shortcuts.newChatDesc"), keys: ["Ctrl+N", "Ctrl+Shift+O"] },
  { name: t("settings.shortcuts.openSideChat"), desc: t("settings.shortcuts.openSideChatDesc"), keys: [] },
  { name: t("settings.shortcuts.openNewWindow"), desc: t("settings.shortcuts.openNewWindowDesc"), keys: [] },
  { name: t("settings.shortcuts.newQuickChat"), desc: t("settings.shortcuts.newQuickChatDesc"), keys: ["Ctrl+Alt+N"] },
  { name: t("settings.shortcuts.togglePin"), desc: t("settings.shortcuts.togglePinDesc"), keys: ["Ctrl+Alt+P"] },
  { name: t("settings.shortcuts.search"), desc: t("settings.shortcuts.searchDesc"), keys: ["Ctrl+F"] },
  { name: t("settings.shortcuts.focusBrowserAddress"), desc: t("settings.shortcuts.focusBrowserAddressDesc"), keys: ["Ctrl+L"] },
  { name: t("settings.shortcuts.goBack"), desc: t("settings.shortcuts.goBackDesc"), keys: ["Ctrl+["] },
  { name: t("settings.shortcuts.goForward"), desc: t("settings.shortcuts.goForwardDesc"), keys: ["Ctrl+]"] },
  { name: t("settings.shortcuts.nextChat"), desc: t("settings.shortcuts.nextChatDesc"), keys: ["Ctrl+Shift+]"] },
  { name: t("settings.shortcuts.prevChat"), desc: t("settings.shortcuts.prevChatDesc"), keys: ["Ctrl+Shift+["] },
  { name: t("settings.shortcuts.openBrowserTab"), desc: t("settings.shortcuts.openBrowserTabDesc"), keys: ["Ctrl+T"] },
  { name: t("settings.shortcuts.openReviewTab"), desc: t("settings.shortcuts.openReviewTabDesc"), keys: [] },
  { name: t("settings.shortcuts.toggleBrowserPanel"), desc: t("settings.shortcuts.toggleBrowserPanelDesc"), keys: ["Ctrl+Shift+B"] },
  { name: t("settings.shortcuts.toggleSidebar"), desc: t("settings.shortcuts.toggleSidebarDesc"), keys: ["Ctrl+B"] },
  { name: t("settings.shortcuts.toggleSidePanel"), desc: t("settings.shortcuts.toggleSidePanelDesc"), keys: ["Ctrl+Alt+B"] },
  { name: t("settings.shortcuts.toggleTerminal"), desc: t("settings.shortcuts.toggleTerminalDesc"), keys: ["Ctrl+J"] },
  { name: t("settings.shortcuts.openFolder"), desc: t("settings.shortcuts.openFolderDesc"), keys: ["Ctrl+O"] },
  { name: t("settings.shortcuts.forceReloadSkill"), desc: t("settings.shortcuts.forceReloadSkillDesc"), keys: [] },
  { name: t("settings.shortcuts.goToSkill"), desc: t("settings.shortcuts.goToSkillDesc"), keys: [] },
  { name: t("settings.shortcuts.installCodexWorkspace"), desc: t("settings.shortcuts.installCodexWorkspaceDesc"), keys: [] },
  { name: t("settings.shortcuts.keyboardShortcuts"), desc: t("settings.shortcuts.keyboardShortcutsDesc"), keys: [] },
  { name: t("settings.shortcuts.mcp"), desc: t("settings.shortcuts.mcpDesc"), keys: [] },
  { name: t("settings.shortcuts.personality"), desc: t("settings.shortcuts.personalityDesc"), keys: [] },
  { name: t("settings.shortcuts.feedback"), desc: t("settings.shortcuts.feedbackDesc"), keys: [] },
  { name: t("settings.shortcuts.signOut"), desc: t("settings.shortcuts.signOutDesc"), keys: [] },
  { name: t("settings.shortcuts.manageAutomations"), desc: t("settings.shortcuts.manageAutomationsDesc"), keys: [] },
  { name: t("settings.shortcuts.wakePet"), desc: t("settings.shortcuts.wakePetDesc"), keys: [] },
  { name: t("settings.shortcuts.openControlWindow"), desc: t("settings.shortcuts.openControlWindowDesc"), keys: [] },
  { name: t("settings.shortcuts.settings"), desc: t("settings.shortcuts.settingsDesc"), keys: ["Ctrl+,"] },
  { name: t("settings.shortcuts.approveRequest"), desc: t("settings.shortcuts.approveRequestDesc"), keys: ["Enter"] },
  { name: t("settings.shortcuts.declineRequest"), desc: t("settings.shortcuts.declineRequestDesc"), keys: ["Escape"] },
  { name: t("settings.shortcuts.close"), desc: t("settings.shortcuts.closeDesc"), keys: ["Ctrl+W"] },
  { name: t("settings.shortcuts.openModelPicker"), desc: t("settings.shortcuts.openModelPickerDesc"), keys: ["Ctrl+Shift+M"] },
  { name: t("settings.shortcuts.startDictation"), desc: t("settings.shortcuts.startDictationDesc"), keys: ["Ctrl+Shift+D"] },
  { name: t("settings.shortcuts.toggleVoiceMode"), desc: t("settings.shortcuts.toggleVoiceModeDesc"), keys: ["Ctrl+Shift+V"] },
  { name: t("settings.shortcuts.copyAsMarkdown"), desc: t("settings.shortcuts.copyAsMarkdownDesc"), keys: [] },
  { name: t("settings.shortcuts.copyConversationPath"), desc: t("settings.shortcuts.copyConversationPathDesc"), keys: ["Ctrl+Alt+Shift+C"] },
  { name: t("settings.shortcuts.copyDeeplink"), desc: t("settings.shortcuts.copyDeeplinkDesc"), keys: ["Ctrl+Alt+L"] },
  { name: t("settings.shortcuts.copySessionId"), desc: t("settings.shortcuts.copySessionIdDesc"), keys: ["Ctrl+Alt+C"] },
  { name: t("settings.shortcuts.copyWorkingDirectory"), desc: t("settings.shortcuts.copyWorkingDirectoryDesc"), keys: ["Ctrl+Shift+C"] },
  { name: t("settings.shortcuts.holdDictationShortcut"), desc: t("settings.shortcuts.holdDictationShortcutDesc"), keys: [] },
  { name: t("settings.shortcuts.toggleDictationShortcut"), desc: t("settings.shortcuts.toggleDictationShortcutDesc"), keys: [] },
  { name: t("settings.shortcuts.forceReloadBrowserPage"), desc: t("settings.shortcuts.forceReloadBrowserPageDesc"), keys: ["Ctrl+Shift+R"] },
  { name: t("settings.shortcuts.popupShortcut"), desc: t("settings.shortcuts.popupShortcutDesc"), keys: [] },
  { name: t("settings.shortcuts.newWindow"), desc: t("settings.shortcuts.newWindowDesc"), keys: ["Ctrl+Shift+N"] },
  { name: t("settings.shortcuts.nextRecentChat"), desc: t("settings.shortcuts.nextRecentChatDesc"), keys: ["Ctrl+Tab"] },
  { name: t("settings.shortcuts.openCommandMenu"), desc: t("settings.shortcuts.openCommandMenuDesc"), keys: ["Ctrl+K", "Ctrl+Shift+P"] },
  { name: t("settings.shortcuts.prevRecentChat"), desc: t("settings.shortcuts.prevRecentChatDesc"), keys: ["Ctrl+Shift+Tab"] },
  { name: t("settings.shortcuts.reloadBrowserPage"), desc: t("settings.shortcuts.reloadBrowserPageDesc"), keys: ["Ctrl+R"] },
  { name: t("settings.shortcuts.renameChat"), desc: t("settings.shortcuts.renameChatDesc"), keys: ["Ctrl+Alt+R"] },
  { name: t("settings.shortcuts.searchChats"), desc: t("settings.shortcuts.searchChatsDesc"), keys: ["Ctrl+G"] },
  { name: t("settings.shortcuts.searchFiles"), desc: t("settings.shortcuts.searchFilesDesc"), keys: ["Ctrl+P"] },
  { name: t("settings.shortcuts.showShortcuts"), desc: t("settings.shortcuts.showShortcutsDesc"), keys: ["Ctrl+Shift+/"] },
  { name: t("settings.shortcuts.goToChat1"), desc: t("settings.shortcuts.goToChat1Desc"), keys: ["Ctrl+1"] },
  { name: t("settings.shortcuts.goToChat2"), desc: t("settings.shortcuts.goToChat2Desc"), keys: ["Ctrl+2"] },
  { name: t("settings.shortcuts.goToChat3"), desc: t("settings.shortcuts.goToChat3Desc"), keys: ["Ctrl+3"] },
  { name: t("settings.shortcuts.goToChat4"), desc: t("settings.shortcuts.goToChat4Desc"), keys: ["Ctrl+4"] },
  { name: t("settings.shortcuts.goToChat5"), desc: t("settings.shortcuts.goToChat5Desc"), keys: ["Ctrl+5"] },
  { name: t("settings.shortcuts.goToChat6"), desc: t("settings.shortcuts.goToChat6Desc"), keys: ["Ctrl+6"] },
  { name: t("settings.shortcuts.goToChat7"), desc: t("settings.shortcuts.goToChat7Desc"), keys: ["Ctrl+7"] },
  { name: t("settings.shortcuts.goToChat8"), desc: t("settings.shortcuts.goToChat8Desc"), keys: ["Ctrl+8"] },
  { name: t("settings.shortcuts.goToChat9"), desc: t("settings.shortcuts.goToChat9Desc"), keys: ["Ctrl+9"] },
  { name: t("settings.shortcuts.toggleFileTree"), desc: t("settings.shortcuts.toggleFileTreeDesc"), keys: ["Ctrl+Shift+E"] },
  { name: t("settings.shortcuts.startTraceRecording"), desc: t("settings.shortcuts.startTraceRecordingDesc"), keys: ["Ctrl+Shift+5"] },
];
