/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{ts,tsx}"],
  theme: {
    extend: {
      colors: {
        primary: "var(--theme-accent, #111827)",
        "primary-hover": "var(--theme-accent-hover, #000000)",
        "bg-base": "var(--theme-bg, #ffffff)",
        "text-base": "var(--theme-fg, #1F2937)",
        "text-secondary": "var(--theme-text-secondary, #6B7280)",
        "border-theme": "var(--theme-border, #E5E7EB)",
        "sidebar-bg": "var(--theme-sidebar, #F9F8F6)",
        "elevated-bg": "var(--theme-elevated, #FFFFFF)",
        "hover-bg": "var(--theme-hover, #F3F4F6)",
        "selection-bg": "var(--theme-selection, #DBEAFE)",
        "reasoning-simple-from": "var(--theme-reasoning-simple-from, #8ECBC6)",
        "reasoning-simple-mid": "var(--theme-reasoning-simple-mid, #A9DAD0)",
        "reasoning-simple-to": "var(--theme-reasoning-simple-to, #C9E8DF)",
        "reasoning-medium-from": "var(--theme-reasoning-medium-from, #48BFC0)",
        "reasoning-medium-mid": "var(--theme-reasoning-medium-mid, #55CDAE)",
        "reasoning-medium-to": "var(--theme-reasoning-medium-to, #91E0C9)",
        "reasoning-deep-from": "var(--theme-reasoning-deep-from, #22B8C0)",
        "reasoning-deep-mid": "var(--theme-reasoning-deep-mid, #1FC28F)",
        "reasoning-deep-to": "var(--theme-reasoning-deep-to, #45D9A0)",
      },
      fontFamily: {
        sans: [
          "var(--ui-font, Inter)",
          "-apple-system",
          "BlinkMacSystemFont",
          '"Segoe UI"',
          "Roboto",
          '"Helvetica Neue"',
          "Arial",
          "sans-serif",
        ],
        mono: [
          "var(--code-font, ui-monospace)",
          "SFMono-Regular",
          "Menlo",
          "Monaco",
          "Consolas",
          '"Liberation Mono"',
          '"Courier New"',
          "monospace",
        ],
      },
    },
  },
  plugins: [],
};
